### ISSUE TITLE
Reduced config leads to error

### ISSUE THREAD

**Issue by c33s** [humbug/box#167]
```yaml
compactors:
   - Herrera\Box\Compactor\Json
   - Herrera\Box\Compactor\Php
compression: GZ
output: build/puppet-enc.phar
git-commit: git_commit
git-version: git_version
git-tag: git_tag
chmod: '0755'
```
->
```json
{
    "compactors": [
        "Herrera\\Box\\Compactor\\Json",
        "Herrera\\Box\\Compactor\\Php"
    ],
    "compression": "GZ",
    "output": "build/puppet-enc.phar",
    "git-commit": "git_commit",
    "git-version": "git_version",
    "git-tag": "git_tag",
    "chmod": "0755"
}
```
->
```
 [ERROR] The configuration file is invalid.

In Assertion.php line 283:

  [_HumbugBox5adef95163555\Assert\InvalidArgumentException (102)]
  File "puppet-enc/index.php" was expected to exist.
```
